const { BASE_URL } = require('./constants');

const defaultBranches = [
    {
        id: 1,
        slug: 'bangalore-hq',
        name: 'Cypher Swift InfoTech — Bangalore HQ',
        businessType: 'ProfessionalService',
        street: 'Electronic City Phase 1, Hosur Road',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560100',
        country: 'IN',
        phone: '+917204468429',
        website: BASE_URL,
        lat: 12.8456,
        lng: 77.6603,
        rating: 4.8,
        reviewCount: 42,
        openingHours: [{ dayOfWeek: ['Monday-Sunday'], opens: '09:00', closes: '18:00' }],
        deliveryAvailable: true,
        inStorePickup: true,
        imageUrl: `${BASE_URL}/logo.svg`
    },
    {
        id: 2,
        slug: 'mumbai',
        name: 'Cypher Swift InfoTech — Mumbai',
        businessType: 'ProfessionalService',
        street: 'Bandra Kurla Complex, G Block',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400051',
        country: 'IN',
        phone: '+917204468429',
        website: BASE_URL,
        lat: 19.0596,
        lng: 72.8656,
        rating: 4.7,
        reviewCount: 28,
        openingHours: [{ dayOfWeek: ['Monday-Sunday'], opens: '09:00', closes: '18:00' }],
        deliveryAvailable: true,
        inStorePickup: true,
        imageUrl: `${BASE_URL}/logo.svg`
    },
    {
        id: 3,
        slug: 'delhi-ncr',
        name: 'Cypher Swift InfoTech — Delhi NCR',
        businessType: 'ProfessionalService',
        street: 'Cyber Hub, DLF Cyber City',
        city: 'Gurugram',
        state: 'Haryana',
        pincode: '122002',
        country: 'IN',
        phone: '+917204468429',
        website: BASE_URL,
        lat: 28.4941,
        lng: 77.0885,
        rating: 4.6,
        reviewCount: 35,
        openingHours: [{ dayOfWeek: ['Monday-Sunday'], opens: '09:00', closes: '18:00' }],
        deliveryAvailable: true,
        inStorePickup: true,
        imageUrl: `${BASE_URL}/logo.svg`
    },
    {
        id: 4,
        slug: 'hyderabad',
        name: 'Cypher Swift InfoTech — Hyderabad',
        businessType: 'ProfessionalService',
        street: 'HITEC City, Madhapur',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500081',
        country: 'IN',
        phone: '+917204468429',
        website: BASE_URL,
        lat: 17.4486,
        lng: 78.3908,
        rating: 4.7,
        reviewCount: 22,
        openingHours: [{ dayOfWeek: ['Monday-Sunday'], opens: '09:00', closes: '18:00' }],
        deliveryAvailable: true,
        inStorePickup: true,
        imageUrl: `${BASE_URL}/logo.svg`
    },
    {
        id: 5,
        slug: 'pune',
        name: 'Cypher Swift InfoTech — Pune',
        businessType: 'ProfessionalService',
        street: 'Hinjawadi Phase 1, Rajiv Gandhi Infotech Park',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411057',
        country: 'IN',
        phone: '+917204468429',
        website: BASE_URL,
        lat: 18.5912,
        lng: 73.7389,
        rating: 4.5,
        reviewCount: 18,
        openingHours: [{ dayOfWeek: ['Monday-Sunday'], opens: '09:00', closes: '18:00' }],
        deliveryAvailable: true,
        inStorePickup: true,
        imageUrl: `${BASE_URL}/logo.svg`
    }
];

module.exports = { defaultBranches };
